package com.mycompany.semestralkamaven.entity;
// Generated Apr 19, 2016 1:14:28 PM by Hibernate Tools 4.3.1



/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private int idAuthor;
     private String authorName;
     private String authorSurname;

    public Author() {
    }

	
    public Author(int idAuthor) {
        this.idAuthor = idAuthor;
    }
    public Author(int idAuthor, String authorName, String authorSurname) {
       this.idAuthor = idAuthor;
       this.authorName = authorName;
       this.authorSurname = authorSurname;
    }
   
    public int getIdAuthor() {
        return this.idAuthor;
    }
    
    public void setIdAuthor(int idAuthor) {
        this.idAuthor = idAuthor;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public String getAuthorSurname() {
        return this.authorSurname;
    }
    
    public void setAuthorSurname(String authorSurname) {
        this.authorSurname = authorSurname;
    }




}


