package com.mycompany.semestralkamaven.entity;
// Generated Apr 19, 2016 1:14:28 PM by Hibernate Tools 4.3.1



/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private int idBook;
     private int idTitle;
     private Integer price;

    public Book() {
    }

	
    public Book(int idBook, int idTitle) {
        this.idBook = idBook;
        this.idTitle = idTitle;
    }
    public Book(int idBook, int idTitle, Integer price) {
       this.idBook = idBook;
       this.idTitle = idTitle;
       this.price = price;
    }
   
    public int getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(int idBook) {
        this.idBook = idBook;
    }
    public int getIdTitle() {
        return this.idTitle;
    }
    
    public void setIdTitle(int idTitle) {
        this.idTitle = idTitle;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }




}


