package com.mycompany.semestralkamaven.entity;
// Generated Apr 18, 2016 3:42:07 PM by Hibernate Tools 4.3.1



/**
 * Cestujuci generated by hbm2java
 */
public class Cestujuci  implements java.io.Serializable {


     private CestujuciId id;

    public Cestujuci() {
    }

    public Cestujuci(CestujuciId id) {
       this.id = id;
    }
   
    public CestujuciId getId() {
        return this.id;
    }
    
    public void setId(CestujuciId id) {
        this.id = id;
    }




}


