package com.mycompany.semestralkamaven.entity;
// Generated Apr 18, 2016 3:42:07 PM by Hibernate Tools 4.3.1



/**
 * CestujuciId generated by hbm2java
 */
public class CestujuciId  implements java.io.Serializable {


     private int rc;
     private int idLet;

    public CestujuciId() {
    }

    public CestujuciId(int rc, int idLet) {
       this.rc = rc;
       this.idLet = idLet;
    }
   
    public int getRc() {
        return this.rc;
    }
    
    public void setRc(int rc) {
        this.rc = rc;
    }
    public int getIdLet() {
        return this.idLet;
    }
    
    public void setIdLet(int idLet) {
        this.idLet = idLet;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CestujuciId) ) return false;
		 CestujuciId castOther = ( CestujuciId ) other; 
         
		 return (this.getRc()==castOther.getRc())
 && (this.getIdLet()==castOther.getIdLet());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRc();
         result = 37 * result + this.getIdLet();
         return result;
   }   


}


