package com.mycompany.semestralkamaven.entity;
// Generated Apr 18, 2016 3:42:07 PM by Hibernate Tools 4.3.1



/**
 * Kapitan generated by hbm2java
 */
public class Kapitan  implements java.io.Serializable {


     private int rc;
     private int nalietanehodiny;

    public Kapitan() {
    }

    public Kapitan(int rc, int nalietanehodiny) {
       this.rc = rc;
       this.nalietanehodiny = nalietanehodiny;
    }
   
    public int getRc() {
        return this.rc;
    }
    
    public void setRc(int rc) {
        this.rc = rc;
    }
    public int getNalietanehodiny() {
        return this.nalietanehodiny;
    }
    
    public void setNalietanehodiny(int nalietanehodiny) {
        this.nalietanehodiny = nalietanehodiny;
    }




}


