package com.mycompany.semestralkamaven.entity;
// Generated Apr 18, 2016 3:42:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Let generated by hbm2java
 */
public class Let  implements java.io.Serializable {


     private int idLet;
     private Date datumodletu;
     private String destinacia;
     private Integer kapitan;

    public Let() {
    }

	
    public Let(int idLet, Date datumodletu, String destinacia) {
        this.idLet = idLet;
        this.datumodletu = datumodletu;
        this.destinacia = destinacia;
    }
    public Let(int idLet, Date datumodletu, String destinacia, Integer kapitan) {
       this.idLet = idLet;
       this.datumodletu = datumodletu;
       this.destinacia = destinacia;
       this.kapitan = kapitan;
    }
   
    public int getIdLet() {
        return this.idLet;
    }
    
    public void setIdLet(int idLet) {
        this.idLet = idLet;
    }
    public Date getDatumodletu() {
        return this.datumodletu;
    }
    
    public void setDatumodletu(Date datumodletu) {
        this.datumodletu = datumodletu;
    }
    public String getDestinacia() {
        return this.destinacia;
    }
    
    public void setDestinacia(String destinacia) {
        this.destinacia = destinacia;
    }
    public Integer getKapitan() {
        return this.kapitan;
    }
    
    public void setKapitan(Integer kapitan) {
        this.kapitan = kapitan;
    }




}


