package com.mycompany.semestralkamaven.entity;
// Generated Apr 18, 2016 3:42:07 PM by Hibernate Tools 4.3.1



/**
 * Osoba generated by hbm2java
 */
public class Osoba  implements java.io.Serializable {


     private int rc;
     private String meno;
     private String priezvisko;

    public Osoba() {
    }

    public Osoba(int rc, String meno, String priezvisko) {
       this.rc = rc;
       this.meno = meno;
       this.priezvisko = priezvisko;
    }
   
    public int getRc() {
        return this.rc;
    }
    
    public void setRc(int rc) {
        this.rc = rc;
    }
    public String getMeno() {
        return this.meno;
    }
    
    public void setMeno(String meno) {
        this.meno = meno;
    }
    public String getPriezvisko() {
        return this.priezvisko;
    }
    
    public void setPriezvisko(String priezvisko) {
        this.priezvisko = priezvisko;
    }




}


