package com.mycompany.semestralkamaven.entity;
// Generated Apr 19, 2016 1:14:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RentBook generated by hbm2java
 */
public class RentBook  implements java.io.Serializable {


     private int idRentBook;
     private int idBook;
     private int idReader;
     private Date rentFrom;
     private Date returnDate;

    public RentBook() {
    }

	
    public RentBook(int idRentBook, int idBook, int idReader, Date rentFrom) {
        this.idRentBook = idRentBook;
        this.idBook = idBook;
        this.idReader = idReader;
        this.rentFrom = rentFrom;
    }
    public RentBook(int idRentBook, int idBook, int idReader, Date rentFrom, Date returnDate) {
       this.idRentBook = idRentBook;
       this.idBook = idBook;
       this.idReader = idReader;
       this.rentFrom = rentFrom;
       this.returnDate = returnDate;
    }
   
    public int getIdRentBook() {
        return this.idRentBook;
    }
    
    public void setIdRentBook(int idRentBook) {
        this.idRentBook = idRentBook;
    }
    public int getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(int idBook) {
        this.idBook = idBook;
    }
    public int getIdReader() {
        return this.idReader;
    }
    
    public void setIdReader(int idReader) {
        this.idReader = idReader;
    }
    public Date getRentFrom() {
        return this.rentFrom;
    }
    
    public void setRentFrom(Date rentFrom) {
        this.rentFrom = rentFrom;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }




}


