package com.mycompany.semestralkamaven.entity;
// Generated Apr 19, 2016 1:14:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Title generated by hbm2java
 */
public class Title  implements java.io.Serializable {


     private int idTitle;
     private int idAuthor;
     private String titleName;
     private Date publishDate;
     private String genre;

    public Title() {
    }

	
    public Title(int idTitle, int idAuthor, String titleName, Date publishDate) {
        this.idTitle = idTitle;
        this.idAuthor = idAuthor;
        this.titleName = titleName;
        this.publishDate = publishDate;
    }
    public Title(int idTitle, int idAuthor, String titleName, Date publishDate, String genre) {
       this.idTitle = idTitle;
       this.idAuthor = idAuthor;
       this.titleName = titleName;
       this.publishDate = publishDate;
       this.genre = genre;
    }
   
    public int getIdTitle() {
        return this.idTitle;
    }
    
    public void setIdTitle(int idTitle) {
        this.idTitle = idTitle;
    }
    public int getIdAuthor() {
        return this.idAuthor;
    }
    
    public void setIdAuthor(int idAuthor) {
        this.idAuthor = idAuthor;
    }
    public String getTitleName() {
        return this.titleName;
    }
    
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }
    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }




}


