/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.semestralkamaven.ui;

import com.mycompany.semestralkamaven.entity.*;
import com.mycompany.semestralkamaven.util.HibernateUtil;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Filip
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form OsobaGUI
     */
    public Admin() {
        initComponents();
    }

    private static String QUERY_BASED_ON_FIRST_NAME = "from Person where person_name like '";
    private static String QUERY_BASED_ON_LAST_NAME = "from Person where person_surname like '";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOsoba = new javax.swing.JLabel();
        jLabelMeno = new javax.swing.JLabel();
        jLabelPriezvisko = new javax.swing.JLabel();
        jLabelRodneCislo = new javax.swing.JLabel();
        jTextFieldMeno = new javax.swing.JTextField();
        jTextFieldRodneCislo = new javax.swing.JTextField();
        jTextFieldPriezv = new javax.swing.JTextField();
        jButtonQuerry = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOsoba = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelOsoba.setText("Osoba");

        jLabelMeno.setText("Meno");

        jLabelPriezvisko.setText("Priezvisko");

        jLabelRodneCislo.setText("Rodné číslo");

        jTextFieldMeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMenoActionPerformed(evt);
            }
        });

        jButtonQuerry.setText("Query");
        jButtonQuerry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuerryActionPerformed(evt);
            }
        });

        jTableOsoba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableOsoba);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMeno)
                            .addComponent(jLabelRodneCislo))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMeno)
                            .addComponent(jTextFieldRodneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOsoba)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPriezvisko)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPriezv)
                                    .addComponent(jButtonQuerry, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOsoba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMeno)
                    .addComponent(jLabelPriezvisko)
                    .addComponent(jTextFieldMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPriezv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRodneCislo)
                    .addComponent(jTextFieldRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQuerry))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMenoActionPerformed

    private void jButtonQuerryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuerryActionPerformed
        if (!jTextFieldMeno.getText().trim().equals("")) {
            runQueryBasedOnFirstName();
        } else if (!jTextFieldPriezv.getText().trim().equals("")) {
            runQueryBasedOnLastName();
        }
    }//GEN-LAST:event_jButtonQuerryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    private void runQueryBasedOnFirstName() {
        executeHQLQuery(QUERY_BASED_ON_FIRST_NAME + jTextFieldMeno.getText() + "%'");
    }

    private void runQueryBasedOnLastName() {
        executeHQLQuery(QUERY_BASED_ON_LAST_NAME + jTextFieldPriezv.getText() + "%'");
    }

    private void executeHQLQuery(String hql) {
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(hql);
            List resultList = q.list();
            displayResult(resultList);
            session.getTransaction().commit();
        } catch (HibernateException he) {
            he.printStackTrace();
        }
    }

    private void displayResult(List resultList) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("ID");
        tableHeaders.add("Meno");
        tableHeaders.add("Priezvisko");

        for (Object p : resultList) {
            Person person = (Person) p;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(person.getIdOsoba());
            oneRow.add(person.getPersonName());
            oneRow.add(person.getPersonSurname());
            tableData.add(oneRow);
        }
        jTableOsoba.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuerry;
    private javax.swing.JLabel jLabelMeno;
    private javax.swing.JLabel jLabelOsoba;
    private javax.swing.JLabel jLabelPriezvisko;
    private javax.swing.JLabel jLabelRodneCislo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOsoba;
    private javax.swing.JTextField jTextFieldMeno;
    private javax.swing.JTextField jTextFieldPriezv;
    private javax.swing.JTextField jTextFieldRodneCislo;
    // End of variables declaration//GEN-END:variables
}
